name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build package (wheel)
        run: |
          python setup.py sdist bdist_wheel

      - name: Run tests
        run: |
          pytest --junitxml=report.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.xml

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: dist-package
          path: dist/
